// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.32
// source: protobuf.proto

package drpc_example

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_protobuf_proto struct{}

func (drpcEncoding_File_protobuf_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_protobuf_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_protobuf_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_protobuf_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_protobuf_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCGreeterClient interface {
	DRPCConn() drpc.Conn

	SayHello(ctx context.Context, in *HelloRequest) (*HelloReply, error)
}

type drpcGreeterClient struct {
	cc drpc.Conn
}

func NewDRPCGreeterClient(cc drpc.Conn) DRPCGreeterClient {
	return &drpcGreeterClient{cc}
}

func (c *drpcGreeterClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcGreeterClient) SayHello(ctx context.Context, in *HelloRequest) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/drpcf.Greeter/SayHello", drpcEncoding_File_protobuf_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCGreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

type DRPCGreeterUnimplementedServer struct{}

func (s *DRPCGreeterUnimplementedServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCGreeterDescription struct{}

func (DRPCGreeterDescription) NumMethods() int { return 1 }

func (DRPCGreeterDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/drpcf.Greeter/SayHello", drpcEncoding_File_protobuf_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCGreeterServer).
					SayHello(
						ctx,
						in1.(*HelloRequest),
					)
			}, DRPCGreeterServer.SayHello, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterGreeter(mux drpc.Mux, impl DRPCGreeterServer) error {
	return mux.Register(impl, DRPCGreeterDescription{})
}

type DRPCGreeter_SayHelloStream interface {
	drpc.Stream
	SendAndClose(*HelloReply) error
}

type drpcGreeter_SayHelloStream struct {
	drpc.Stream
}

func (x *drpcGreeter_SayHelloStream) SendAndClose(m *HelloReply) error {
	if err := x.MsgSend(m, drpcEncoding_File_protobuf_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
